/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSyndicateRouteRouteImport } from './routes/_authenticated/syndicate/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAiChatRouteRouteImport } from './routes/_authenticated/ai-chat/route'
import { Route as AuthenticatedSyndicateIndexRouteImport } from './routes/_authenticated/syndicate/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedGodIndexRouteImport } from './routes/_authenticated/god/index'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community/index'
import { Route as AuthenticatedAiChatIndexRouteImport } from './routes/_authenticated/ai-chat/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSyndicateCalendarRouteImport } from './routes/_authenticated/syndicate/calendar'
import { Route as AuthenticatedSyndicateBoardRouteImport } from './routes/_authenticated/syndicate/board'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsMemoriesRouteImport } from './routes/_authenticated/settings/memories'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedOrganizationSettingsRouteImport } from './routes/_authenticated/organization/settings'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAiChatBackupRouteImport } from './routes/_authenticated/ai-chat.backup'
import { Route as AuthenticatedAiChatConversationIdRouteImport } from './routes/_authenticated/ai-chat/$conversationId'
import { Route as AuthenticatedAdminGodDashboardRouteImport } from './routes/_authenticated/admin/god-dashboard'
import { Route as authSignupTokenRouteImport } from './routes/(auth)/signup.$token'
import { Route as AuthenticatedSyndicateClassroomRouteRouteImport } from './routes/_authenticated/syndicate/classroom.route'
import { Route as AuthenticatedSyndicateClassroomIndexRouteImport } from './routes/_authenticated/syndicate/classroom.index'
import { Route as AuthenticatedSyndicateClassroomBuilderRouteImport } from './routes/_authenticated/syndicate/classroom.builder'
import { Route as AuthenticatedSyndicateClassroomCourseIdRouteImport } from './routes/_authenticated/syndicate/classroom.$courseId'
import { Route as AuthenticatedSyndicateBoardThreadIdRouteImport } from './routes/_authenticated/syndicate/board.$threadId'
import { Route as AuthenticatedSyndicateClassroomCourseIdLessonIdRouteImport } from './routes/_authenticated/syndicate/classroom.$courseId.$lessonId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSyndicateRouteRoute =
  AuthenticatedSyndicateRouteRouteImport.update({
    id: '/syndicate',
    path: '/syndicate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiChatRouteRoute =
  AuthenticatedAiChatRouteRouteImport.update({
    id: '/ai-chat',
    path: '/ai-chat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSyndicateIndexRoute =
  AuthenticatedSyndicateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSyndicateRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedGodIndexRoute = AuthenticatedGodIndexRouteImport.update({
  id: '/god/',
  path: '/god/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiChatIndexRoute =
  AuthenticatedAiChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAiChatRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyndicateCalendarRoute =
  AuthenticatedSyndicateCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedSyndicateRouteRoute,
  } as any)
const AuthenticatedSyndicateBoardRoute =
  AuthenticatedSyndicateBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AuthenticatedSyndicateRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsMemoriesRoute =
  AuthenticatedSettingsMemoriesRouteImport.update({
    id: '/memories',
    path: '/memories',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationSettingsRoute =
  AuthenticatedOrganizationSettingsRouteImport.update({
    id: '/organization/settings',
    path: '/organization/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiChatBackupRoute =
  AuthenticatedAiChatBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAiChatRouteRoute,
  } as any)
const AuthenticatedAiChatConversationIdRoute =
  AuthenticatedAiChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedAiChatRouteRoute,
  } as any)
const AuthenticatedAdminGodDashboardRoute =
  AuthenticatedAdminGodDashboardRouteImport.update({
    id: '/admin/god-dashboard',
    path: '/admin/god-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authSignupTokenRoute = authSignupTokenRouteImport.update({
  id: '/(auth)/signup/$token',
  path: '/signup/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSyndicateClassroomRouteRoute =
  AuthenticatedSyndicateClassroomRouteRouteImport.update({
    id: '/classroom',
    path: '/classroom',
    getParentRoute: () => AuthenticatedSyndicateRouteRoute,
  } as any)
const AuthenticatedSyndicateClassroomIndexRoute =
  AuthenticatedSyndicateClassroomIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSyndicateClassroomRouteRoute,
  } as any)
const AuthenticatedSyndicateClassroomBuilderRoute =
  AuthenticatedSyndicateClassroomBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => AuthenticatedSyndicateClassroomRouteRoute,
  } as any)
const AuthenticatedSyndicateClassroomCourseIdRoute =
  AuthenticatedSyndicateClassroomCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedSyndicateClassroomRouteRoute,
  } as any)
const AuthenticatedSyndicateBoardThreadIdRoute =
  AuthenticatedSyndicateBoardThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedSyndicateBoardRoute,
  } as any)
const AuthenticatedSyndicateClassroomCourseIdLessonIdRoute =
  AuthenticatedSyndicateClassroomCourseIdLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => AuthenticatedSyndicateClassroomCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/ai-chat': typeof AuthenticatedAiChatRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/syndicate': typeof AuthenticatedSyndicateRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/syndicate/classroom': typeof AuthenticatedSyndicateClassroomRouteRouteWithChildren
  '/signup/$token': typeof authSignupTokenRoute
  '/admin/god-dashboard': typeof AuthenticatedAdminGodDashboardRoute
  '/ai-chat/$conversationId': typeof AuthenticatedAiChatConversationIdRoute
  '/ai-chat/backup': typeof AuthenticatedAiChatBackupRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/organization/settings': typeof AuthenticatedOrganizationSettingsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/memories': typeof AuthenticatedSettingsMemoriesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/syndicate/board': typeof AuthenticatedSyndicateBoardRouteWithChildren
  '/syndicate/calendar': typeof AuthenticatedSyndicateCalendarRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/ai-chat/': typeof AuthenticatedAiChatIndexRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/god': typeof AuthenticatedGodIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/syndicate/': typeof AuthenticatedSyndicateIndexRoute
  '/syndicate/board/$threadId': typeof AuthenticatedSyndicateBoardThreadIdRoute
  '/syndicate/classroom/$courseId': typeof AuthenticatedSyndicateClassroomCourseIdRouteWithChildren
  '/syndicate/classroom/builder': typeof AuthenticatedSyndicateClassroomBuilderRoute
  '/syndicate/classroom/': typeof AuthenticatedSyndicateClassroomIndexRoute
  '/syndicate/classroom/$courseId/$lessonId': typeof AuthenticatedSyndicateClassroomCourseIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/signup/$token': typeof authSignupTokenRoute
  '/admin/god-dashboard': typeof AuthenticatedAdminGodDashboardRoute
  '/ai-chat/$conversationId': typeof AuthenticatedAiChatConversationIdRoute
  '/ai-chat/backup': typeof AuthenticatedAiChatBackupRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/organization/settings': typeof AuthenticatedOrganizationSettingsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/memories': typeof AuthenticatedSettingsMemoriesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/syndicate/board': typeof AuthenticatedSyndicateBoardRouteWithChildren
  '/syndicate/calendar': typeof AuthenticatedSyndicateCalendarRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/ai-chat': typeof AuthenticatedAiChatIndexRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/god': typeof AuthenticatedGodIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/syndicate': typeof AuthenticatedSyndicateIndexRoute
  '/syndicate/board/$threadId': typeof AuthenticatedSyndicateBoardThreadIdRoute
  '/syndicate/classroom/$courseId': typeof AuthenticatedSyndicateClassroomCourseIdRouteWithChildren
  '/syndicate/classroom/builder': typeof AuthenticatedSyndicateClassroomBuilderRoute
  '/syndicate/classroom': typeof AuthenticatedSyndicateClassroomIndexRoute
  '/syndicate/classroom/$courseId/$lessonId': typeof AuthenticatedSyndicateClassroomCourseIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/ai-chat': typeof AuthenticatedAiChatRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/syndicate': typeof AuthenticatedSyndicateRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/syndicate/classroom': typeof AuthenticatedSyndicateClassroomRouteRouteWithChildren
  '/(auth)/signup/$token': typeof authSignupTokenRoute
  '/_authenticated/admin/god-dashboard': typeof AuthenticatedAdminGodDashboardRoute
  '/_authenticated/ai-chat/$conversationId': typeof AuthenticatedAiChatConversationIdRoute
  '/_authenticated/ai-chat/backup': typeof AuthenticatedAiChatBackupRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/organization/settings': typeof AuthenticatedOrganizationSettingsRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/memories': typeof AuthenticatedSettingsMemoriesRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/syndicate/board': typeof AuthenticatedSyndicateBoardRouteWithChildren
  '/_authenticated/syndicate/calendar': typeof AuthenticatedSyndicateCalendarRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/ai-chat/': typeof AuthenticatedAiChatIndexRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/_authenticated/god/': typeof AuthenticatedGodIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/syndicate/': typeof AuthenticatedSyndicateIndexRoute
  '/_authenticated/syndicate/board/$threadId': typeof AuthenticatedSyndicateBoardThreadIdRoute
  '/_authenticated/syndicate/classroom/$courseId': typeof AuthenticatedSyndicateClassroomCourseIdRouteWithChildren
  '/_authenticated/syndicate/classroom/builder': typeof AuthenticatedSyndicateClassroomBuilderRoute
  '/_authenticated/syndicate/classroom/': typeof AuthenticatedSyndicateClassroomIndexRoute
  '/_authenticated/syndicate/classroom/$courseId/$lessonId': typeof AuthenticatedSyndicateClassroomCourseIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ai-chat'
    | '/settings'
    | '/syndicate'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/syndicate/classroom'
    | '/signup/$token'
    | '/admin/god-dashboard'
    | '/ai-chat/$conversationId'
    | '/ai-chat/backup'
    | '/errors/$error'
    | '/organization/settings'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/memories'
    | '/settings/profile'
    | '/syndicate/board'
    | '/syndicate/calendar'
    | '/admin'
    | '/ai-chat/'
    | '/community'
    | '/god'
    | '/settings/'
    | '/syndicate/'
    | '/syndicate/board/$threadId'
    | '/syndicate/classroom/$courseId'
    | '/syndicate/classroom/builder'
    | '/syndicate/classroom/'
    | '/syndicate/classroom/$courseId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/signup/$token'
    | '/admin/god-dashboard'
    | '/ai-chat/$conversationId'
    | '/ai-chat/backup'
    | '/errors/$error'
    | '/organization/settings'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/memories'
    | '/settings/profile'
    | '/syndicate/board'
    | '/syndicate/calendar'
    | '/admin'
    | '/ai-chat'
    | '/community'
    | '/god'
    | '/settings'
    | '/syndicate'
    | '/syndicate/board/$threadId'
    | '/syndicate/classroom/$courseId'
    | '/syndicate/classroom/builder'
    | '/syndicate/classroom'
    | '/syndicate/classroom/$courseId/$lessonId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/ai-chat'
    | '/_authenticated/settings'
    | '/_authenticated/syndicate'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/syndicate/classroom'
    | '/(auth)/signup/$token'
    | '/_authenticated/admin/god-dashboard'
    | '/_authenticated/ai-chat/$conversationId'
    | '/_authenticated/ai-chat/backup'
    | '/_authenticated/errors/$error'
    | '/_authenticated/organization/settings'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/memories'
    | '/_authenticated/settings/profile'
    | '/_authenticated/syndicate/board'
    | '/_authenticated/syndicate/calendar'
    | '/_authenticated/admin/'
    | '/_authenticated/ai-chat/'
    | '/_authenticated/community/'
    | '/_authenticated/god/'
    | '/_authenticated/settings/'
    | '/_authenticated/syndicate/'
    | '/_authenticated/syndicate/board/$threadId'
    | '/_authenticated/syndicate/classroom/$courseId'
    | '/_authenticated/syndicate/classroom/builder'
    | '/_authenticated/syndicate/classroom/'
    | '/_authenticated/syndicate/classroom/$courseId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  authSignupTokenRoute: typeof authSignupTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/syndicate': {
      id: '/_authenticated/syndicate'
      path: '/syndicate'
      fullPath: '/syndicate'
      preLoaderRoute: typeof AuthenticatedSyndicateRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-chat': {
      id: '/_authenticated/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthenticatedAiChatRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syndicate/': {
      id: '/_authenticated/syndicate/'
      path: '/'
      fullPath: '/syndicate/'
      preLoaderRoute: typeof AuthenticatedSyndicateIndexRouteImport
      parentRoute: typeof AuthenticatedSyndicateRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/god/': {
      id: '/_authenticated/god/'
      path: '/god'
      fullPath: '/god'
      preLoaderRoute: typeof AuthenticatedGodIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-chat/': {
      id: '/_authenticated/ai-chat/'
      path: '/'
      fullPath: '/ai-chat/'
      preLoaderRoute: typeof AuthenticatedAiChatIndexRouteImport
      parentRoute: typeof AuthenticatedAiChatRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syndicate/calendar': {
      id: '/_authenticated/syndicate/calendar'
      path: '/calendar'
      fullPath: '/syndicate/calendar'
      preLoaderRoute: typeof AuthenticatedSyndicateCalendarRouteImport
      parentRoute: typeof AuthenticatedSyndicateRouteRoute
    }
    '/_authenticated/syndicate/board': {
      id: '/_authenticated/syndicate/board'
      path: '/board'
      fullPath: '/syndicate/board'
      preLoaderRoute: typeof AuthenticatedSyndicateBoardRouteImport
      parentRoute: typeof AuthenticatedSyndicateRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/memories': {
      id: '/_authenticated/settings/memories'
      path: '/memories'
      fullPath: '/settings/memories'
      preLoaderRoute: typeof AuthenticatedSettingsMemoriesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/organization/settings': {
      id: '/_authenticated/organization/settings'
      path: '/organization/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-chat/backup': {
      id: '/_authenticated/ai-chat/backup'
      path: '/backup'
      fullPath: '/ai-chat/backup'
      preLoaderRoute: typeof AuthenticatedAiChatBackupRouteImport
      parentRoute: typeof AuthenticatedAiChatRouteRoute
    }
    '/_authenticated/ai-chat/$conversationId': {
      id: '/_authenticated/ai-chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/ai-chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedAiChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedAiChatRouteRoute
    }
    '/_authenticated/admin/god-dashboard': {
      id: '/_authenticated/admin/god-dashboard'
      path: '/admin/god-dashboard'
      fullPath: '/admin/god-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminGodDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/signup/$token': {
      id: '/(auth)/signup/$token'
      path: '/signup/$token'
      fullPath: '/signup/$token'
      preLoaderRoute: typeof authSignupTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/syndicate/classroom': {
      id: '/_authenticated/syndicate/classroom'
      path: '/classroom'
      fullPath: '/syndicate/classroom'
      preLoaderRoute: typeof AuthenticatedSyndicateClassroomRouteRouteImport
      parentRoute: typeof AuthenticatedSyndicateRouteRoute
    }
    '/_authenticated/syndicate/classroom/': {
      id: '/_authenticated/syndicate/classroom/'
      path: '/'
      fullPath: '/syndicate/classroom/'
      preLoaderRoute: typeof AuthenticatedSyndicateClassroomIndexRouteImport
      parentRoute: typeof AuthenticatedSyndicateClassroomRouteRoute
    }
    '/_authenticated/syndicate/classroom/builder': {
      id: '/_authenticated/syndicate/classroom/builder'
      path: '/builder'
      fullPath: '/syndicate/classroom/builder'
      preLoaderRoute: typeof AuthenticatedSyndicateClassroomBuilderRouteImport
      parentRoute: typeof AuthenticatedSyndicateClassroomRouteRoute
    }
    '/_authenticated/syndicate/classroom/$courseId': {
      id: '/_authenticated/syndicate/classroom/$courseId'
      path: '/$courseId'
      fullPath: '/syndicate/classroom/$courseId'
      preLoaderRoute: typeof AuthenticatedSyndicateClassroomCourseIdRouteImport
      parentRoute: typeof AuthenticatedSyndicateClassroomRouteRoute
    }
    '/_authenticated/syndicate/board/$threadId': {
      id: '/_authenticated/syndicate/board/$threadId'
      path: '/$threadId'
      fullPath: '/syndicate/board/$threadId'
      preLoaderRoute: typeof AuthenticatedSyndicateBoardThreadIdRouteImport
      parentRoute: typeof AuthenticatedSyndicateBoardRoute
    }
    '/_authenticated/syndicate/classroom/$courseId/$lessonId': {
      id: '/_authenticated/syndicate/classroom/$courseId/$lessonId'
      path: '/$lessonId'
      fullPath: '/syndicate/classroom/$courseId/$lessonId'
      preLoaderRoute: typeof AuthenticatedSyndicateClassroomCourseIdLessonIdRouteImport
      parentRoute: typeof AuthenticatedSyndicateClassroomCourseIdRoute
    }
  }
}

interface AuthenticatedAiChatRouteRouteChildren {
  AuthenticatedAiChatConversationIdRoute: typeof AuthenticatedAiChatConversationIdRoute
  AuthenticatedAiChatBackupRoute: typeof AuthenticatedAiChatBackupRoute
  AuthenticatedAiChatIndexRoute: typeof AuthenticatedAiChatIndexRoute
}

const AuthenticatedAiChatRouteRouteChildren: AuthenticatedAiChatRouteRouteChildren =
  {
    AuthenticatedAiChatConversationIdRoute:
      AuthenticatedAiChatConversationIdRoute,
    AuthenticatedAiChatBackupRoute: AuthenticatedAiChatBackupRoute,
    AuthenticatedAiChatIndexRoute: AuthenticatedAiChatIndexRoute,
  }

const AuthenticatedAiChatRouteRouteWithChildren =
  AuthenticatedAiChatRouteRoute._addFileChildren(
    AuthenticatedAiChatRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsMemoriesRoute: typeof AuthenticatedSettingsMemoriesRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIntegrationsRoute:
      AuthenticatedSettingsIntegrationsRoute,
    AuthenticatedSettingsMemoriesRoute: AuthenticatedSettingsMemoriesRoute,
    AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSyndicateClassroomCourseIdRouteChildren {
  AuthenticatedSyndicateClassroomCourseIdLessonIdRoute: typeof AuthenticatedSyndicateClassroomCourseIdLessonIdRoute
}

const AuthenticatedSyndicateClassroomCourseIdRouteChildren: AuthenticatedSyndicateClassroomCourseIdRouteChildren =
  {
    AuthenticatedSyndicateClassroomCourseIdLessonIdRoute:
      AuthenticatedSyndicateClassroomCourseIdLessonIdRoute,
  }

const AuthenticatedSyndicateClassroomCourseIdRouteWithChildren =
  AuthenticatedSyndicateClassroomCourseIdRoute._addFileChildren(
    AuthenticatedSyndicateClassroomCourseIdRouteChildren,
  )

interface AuthenticatedSyndicateClassroomRouteRouteChildren {
  AuthenticatedSyndicateClassroomCourseIdRoute: typeof AuthenticatedSyndicateClassroomCourseIdRouteWithChildren
  AuthenticatedSyndicateClassroomBuilderRoute: typeof AuthenticatedSyndicateClassroomBuilderRoute
  AuthenticatedSyndicateClassroomIndexRoute: typeof AuthenticatedSyndicateClassroomIndexRoute
}

const AuthenticatedSyndicateClassroomRouteRouteChildren: AuthenticatedSyndicateClassroomRouteRouteChildren =
  {
    AuthenticatedSyndicateClassroomCourseIdRoute:
      AuthenticatedSyndicateClassroomCourseIdRouteWithChildren,
    AuthenticatedSyndicateClassroomBuilderRoute:
      AuthenticatedSyndicateClassroomBuilderRoute,
    AuthenticatedSyndicateClassroomIndexRoute:
      AuthenticatedSyndicateClassroomIndexRoute,
  }

const AuthenticatedSyndicateClassroomRouteRouteWithChildren =
  AuthenticatedSyndicateClassroomRouteRoute._addFileChildren(
    AuthenticatedSyndicateClassroomRouteRouteChildren,
  )

interface AuthenticatedSyndicateBoardRouteChildren {
  AuthenticatedSyndicateBoardThreadIdRoute: typeof AuthenticatedSyndicateBoardThreadIdRoute
}

const AuthenticatedSyndicateBoardRouteChildren: AuthenticatedSyndicateBoardRouteChildren =
  {
    AuthenticatedSyndicateBoardThreadIdRoute:
      AuthenticatedSyndicateBoardThreadIdRoute,
  }

const AuthenticatedSyndicateBoardRouteWithChildren =
  AuthenticatedSyndicateBoardRoute._addFileChildren(
    AuthenticatedSyndicateBoardRouteChildren,
  )

interface AuthenticatedSyndicateRouteRouteChildren {
  AuthenticatedSyndicateClassroomRouteRoute: typeof AuthenticatedSyndicateClassroomRouteRouteWithChildren
  AuthenticatedSyndicateBoardRoute: typeof AuthenticatedSyndicateBoardRouteWithChildren
  AuthenticatedSyndicateCalendarRoute: typeof AuthenticatedSyndicateCalendarRoute
  AuthenticatedSyndicateIndexRoute: typeof AuthenticatedSyndicateIndexRoute
}

const AuthenticatedSyndicateRouteRouteChildren: AuthenticatedSyndicateRouteRouteChildren =
  {
    AuthenticatedSyndicateClassroomRouteRoute:
      AuthenticatedSyndicateClassroomRouteRouteWithChildren,
    AuthenticatedSyndicateBoardRoute:
      AuthenticatedSyndicateBoardRouteWithChildren,
    AuthenticatedSyndicateCalendarRoute: AuthenticatedSyndicateCalendarRoute,
    AuthenticatedSyndicateIndexRoute: AuthenticatedSyndicateIndexRoute,
  }

const AuthenticatedSyndicateRouteRouteWithChildren =
  AuthenticatedSyndicateRouteRoute._addFileChildren(
    AuthenticatedSyndicateRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiChatRouteRoute: typeof AuthenticatedAiChatRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSyndicateRouteRoute: typeof AuthenticatedSyndicateRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminGodDashboardRoute: typeof AuthenticatedAdminGodDashboardRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedOrganizationSettingsRoute: typeof AuthenticatedOrganizationSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
  AuthenticatedGodIndexRoute: typeof AuthenticatedGodIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiChatRouteRoute: AuthenticatedAiChatRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSyndicateRouteRoute:
    AuthenticatedSyndicateRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminGodDashboardRoute: AuthenticatedAdminGodDashboardRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedOrganizationSettingsRoute:
    AuthenticatedOrganizationSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
  AuthenticatedGodIndexRoute: AuthenticatedGodIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  authSignupTokenRoute: authSignupTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
